#!/bin/bash
JSON_FILE="data.json"
name=$(jq -r '.name' "$JSON_FILE" | sed 's/.*/\u&/')
height=$(jq -r '.height' "$JSON_FILE" | awk '{print $1/10}')
weight=$(jq -r '.weight' "$JSON_FILE" | awk '{print $1/10}')
type=$(jq -r '.types[0].type.name' "$JSON_FILE" | sed 's/.*/\u&/')
echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."
